# @package _global_

# data 
Dataset: cifar10
data:
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false

final_adaptive: True
adaptive_mean: False
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: 1 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])
load: False

# device
device: cuda
dataparallel: True
num_workers: 8 
pin_memory: True
distributed: False

# logging
log_stride : 10
gif_stride: 5000

# training
cache_npar: 10000
use_prev_net: False
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
nit : 250
plot_npar: 100
n_ipf_init: 1
batch_size: 128
num_iter : 500000
n_ipf: 20
lr: 0.0001
gamma_max: 0.1
gamma_min: 0.00001
gamma_space: linspace
weight_distrib: True
weight_distrib_alpha: 100
corrector: False
fast_sampling: True


# checkpoint
checkpoint_run: False
checkpoint_it: 1
checkpoint_pass: backward
sample_checkpoint_b: /home/thornton/20-schrodinger/code/scripts/experiments/2021-04-29/main/cache_npar=1000,checkpoint_run=False/13-24-38/checkpoints/sample_net_backward_1_15000.ckpt