# @package _global_

defaults:
  - launcher: local
  - job
  - dataset: stackedmnist #celeba, 2d, stackedmnist
  - hydra/launcher: basic 
  - model: UNET #Basic, DDPM, NCSN, NCSNv1
  

# data

#data_dir:  /data/greyostrich/oxwasp/oxwasp18/thornton/20-schrodinger/data/
data_dir: /home/james/schrodinger_bridge/data/
#data_dir: /home/thornton/20-schrodinger/data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
NEPTUNE_TOKEN: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiODE5YjBiZGYtN2ZiYS00YWU0LTg3N2MtZDBiNWMyN2QwZjEwIn0=
NEPTUNE_PROJECT: 'CompStats/SchrodingerBridge'
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 10
cache_refresh_stride: 1000
num_data_classes: 0
plot_level: 2
paths: 
  experiments_dir_name: experiments

weight_decay: 0.0
save_interval: 5000

out_dir: output