# @package _global_

defaults:
  - launcher: local
  - job
  - dataset: stackedmnist #celeba, 2d, stackedmnist
  - hydra/launcher: basic 
  - model: UNET #Basic, DDPM, NCSN, NCSNv1
  

# data

#data_dir:  /data/greyostrich/oxwasp/oxwasp18/thornton/20-schrodinger/data/
data_dir: /home/thornton/schrodinger_bridge/data/
#data_dir: /home/thornton/20-schrodinger/data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
NEPTUNE_TOKEN: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiODE5YjBiZGYtN2ZiYS00YWU0LTg3N2MtZDBiNWMyN2QwZjEwIn0=
NEPTUNE_PROJECT: 'CompStats/SchrodingerBridge'
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 1
cache_refresh_stride: 1000
num_data_classes: 0
plot_level: 2
paths: 
  experiments_dir_name: experiments

weight_decay: 0.0
save_interval: 5000
transfer: False
out_dir: output
t_batch: 32
start_backward: True
start_model_checkpoint_forward: None # /home/james/schrodinger_bridge/scripts/experiments/2021-05-26/main/batch_size=32,cache_npar=128,cache_refresh_stride=100,model.num_channels=64,nit=150,num_iter=10000,start_backward=False/18-12-22/output/forward/1/checkpoints/model010000.pt
start_model_checkpoint_backward: /home/thornton/schrodinger_bridge/scripts/experiments/2021-05-27/main/batch_size=32,cache_npar=128,cache_refresh_stride=100,data.image_size=64,model.num_channels=128,nit=200,num_iter=200000,start_backward=True/16-10-32/output/backward/0/checkpoints/model050000.pt
start_sample_checkpoint: /home/thornton/schrodinger_bridge/scripts/experiments/2021-05-27/main/batch_size=32,cache_npar=128,cache_refresh_stride=100,data.image_size=64,model.num_channels=128,nit=200,num_iter=200000,start_backward=True/16-10-32/output/backward/0/checkpoints/ema_0.999_050000.pt
ipf_start: 0